---
name: CI

on:
  push:
  pull_request:

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'
  # Mudar a cor de mensagens de debug para aparecer melhor no fundo
  # escuro dos logs do GitHub Action.
  ANSIBLE_COLOR_DEBUG: "bright gray"

jobs:
  python-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install --deploy
  docker-deps:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        molecule_distro: [ubuntu1804, ubuntu2004]
    steps:
      - name: Save ${{ matrix.molecule_distro }} image
        run: |
          docker save geerlingguy/docker-${{ matrix.molecule_disro }}-ansible:latest > ~/cache/${{ matrix.molecule_distro }}.tar.gz
      - name: Cache ${{ matrix.molecule_distro }} image
        uses: actions/cache@v3
        with:
          path: ~/cache/${{ matrix.molecule_distro }}.tar.gz
          key: docker-${{ matrix.molecule_distro }}
  linter:
    needs: python-deps
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install --deploy
      - name: Run Linters
        run: |
          pipenv run molecule lint

  molecule:
    needs: [python-deps, docker-deps]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        molecule_distro: [ubuntu1804, ubuntu2004]
    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install --deploy
      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
      - name: Load cached Docker image
        uses: actions/cache@v3
        with:
          path: ~/cache/${{ matrix.molecule_distro }}.tar.gz
          key: docker-${{ matrix.molecule_distro }}
      - run: docker load --input ~/cache/${{ matrix.molecule_distro }}.tar.gz
      - name: Test with molecule
        run: |
          pipenv run molecule test --all
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
